import { type NextPage } from "next";
import Head from "next/head";

import Docs from "src/components/docs";
import Predictor from "../components/predictor";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>F1 Race Predictor</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col md:flex-row min-h-screen font-inter">
        <section className="md:fixed md:overflow-auto md:left-0 md:overflow-y-auto md:h-full bg-[#161616] px-16 py-12 md:w-1/2 xl:w-1/3 bg-[url('/red-bg.jpg')] bg-cover text-white">
          <Predictor />
        </section>
        <section className="p-16 md:py-24 md:px-16 xl:px-28 md:w-1/2 xl:w-2/3 md:overflow-y-auto md:fixed md:right-0 md:h-full">
          <article id="871047b8-2997-4a68-9c0f-53ade839e37d" className="page sans">
          <Docs />
          </article>
        </section>
      </main>
    </>
  );
};

export default Home;
